---
all:
  children:
    pfsense:
      hosts:
        fw01.home.caseysparkz.com:
    routeros:
      hosts:
        sw01.home.caseysparkz.com:
        ap01.home.caseysparkz.com:
    network:
      children:
        pfsense:
        routeros:
  hosts:
    localhost:
