---
collections:
  - name: "./collections/caseysparkz/environment"
    version: "1.2.1"

  - name: "./collections/caseysparkz/performance"
    version: "2.0.0"

  - name: "./collections/caseysparkz/security"
    version: "2.0.0"

  - name: "community.routeros"
    version: "3.20.0"

  - name: "pfsensible.core"
    version: "0.7.1"
