---
- name: "[packages.systemd]"
  become: true
  tags: ["systemd"]
  block:
    - name: "[packages.systemd.daemon_reload]"
      ansible.builtin.systemd:
        daemon_reload: true

    - name: "[packages.systemd.services]"
      loop: "{{ packages_systemd.services }}"
      ansible.builtin.systemd:
        name: "{{ item }}.service"
        enabled: true

    - name: "[packages.systemd.sockets]"
      loop: "{{ packages_systemd.sockets }}"
      ansible.builtin.systemd:
        name: "{{ item }}.socket"
        enabled: true

    - name: "[packages.systemd.timers]"
      loop: "{{ packages_systemd.timers }}"
      ansible.builtin.systemd:
        name: "{{ item }}.timer"
        enabled: true
