---
namespace: "caseysparkz"
name: "performance"
version: "1.0.2"
readme: "README.md"
authors: ["Casey Sparks <ansible@caseysparkz.com> (https://www.caseysparkz.com)"]
description: "A collection of performance tweaks for Linux."
license: ["GPL-2.0-or-later"]
tags:
  - "linux"
  - "performance"
dependencies: {}
repository: &repo "https://github.com/caseysparkz/env"
documentation: "https://github.com/caseysparkz/env/blob/collections/caseysparkz/performance/README.md"
homepage: *repo
issues: "https://github.com/caseysparkz/env/issues"
build_ignore: []
