---
namespace: "caseysparkz"
name: "security"
version: "2.0.1"
readme: "README.md"
authors: ["Casey Sparks <ansible@caseysparkz.com> (https://www.caseysparkz.com)"]
description: "A collection of security improvements for Linux systems."
license: ["GPL-2.0-or-later"]
tags:
  - "linux"
  - "security"
dependencies:
  ansible.posix: ">=2.2.0,<3.0.0"
  community.general: ">=13.0.0,<14.0.0"
repository: &repo "https://github.com/caseysparkz/env"
documentation: "https://github.com/caseysparkz/env/blob/main/collections/caseysparkz/security/README.md"
homepage: *repo
issues: "https://github.com/caseysparkz/env/issues"
build_ignore: []
