---
namespace: "caseysparkz"
name: "security"
version: "1.0.2"
readme: "README.md"
authors: ["Casey Sparks <ansible@caseysparkz.com> (https://www.caseysparkz.com)"]
description: "A collection of security improvements for Linux systems."
license: ["GPL-2.0-or-later"]
tags:
  - "linux"
  - "security"
dependencies:
  ansible.posix: ">=2.0.0,<3.0.0"
  community.general: ">=10.7.0,<11.0.0"
repository: &repo "https://github.com/caseysparkz/ansible"
documentation: "https://github.com/caseysparkz/ansible/blob/main/collections/caseysparkz/security/README.md"
homepage: *repo
issues: "https://github.com/caseysparkz/ansible/issues"
build_ignore: []
