#!/usr/bin/env python3
# Copyright (C) 2025
# Author:       Casey Sparks
# Date:         January 25, 2022
# Description:
"""A simple CLI clock."""

from argparse import ArgumentParser, Namespace
from datetime import datetime
from os import system
from sys import exit as sys_exit
from time import sleep


def get_arguments() -> Namespace:
    """Get cmdline arguments.

    Returns:
        argparse.Namespace instance of user arguments.
    """
    parser = ArgumentParser(description=__doc__)

    parser.add_argument("-12", action="store_true", dest="twelve", help="Set format to 12hr time.")  # -12

    return parser.parse_args()


def run_clock(twelve_hour: bool = False) -> None:  # noqa: FBT001,FBT002
    """Continuously display a text-based clock.

    Args:
        twelve_hour: Boolean indicating if clock should show twelve-hour time.
    """
    time_string = "%I:%M:%S %p" if twelve_hour else "%H:%M:%S"
    div = "=" * len(time_string)

    while True:
        try:
            system("clear")  # noqa: S605,S607 - Clear screen
            print(div)
            print(f"{datetime.now().strftime(time_string)}")  # noqa: DTZ005
            print(div)
            sleep(1)  # Sleep one second.

        except KeyboardInterrupt:  # Exit without stack trace
            print()
            sys_exit(0)


if __name__ == "__main__":
    args = get_arguments()

    run_clock(args.twelve)
