#!/usr/bin/env python3
# Copyright (C) 2025
# Author:       Casey Sparks
# Date:         January 25, 2022
# Description:
"""A simple CLI clock."""

from argparse import ArgumentParser, Namespace
from datetime import datetime
from os import system
from sys import exit as sys_exit
from time import sleep


def get_arguments() -> Namespace:
    """Get cmdline arguments.

    Returns:
        argparse.Namespace instance of user arguments.
    """
    parser = ArgumentParser(description=__doc__)

    parser.add_argument("-12", action="store_true", dest="twelve", help="Set format to 12hr time.")

    return parser.parse_args()


def run_clock(time_string: str = "%H:%M:%S") -> None:
    """Continuously display a text-based clock.

    Args:
        time_string: String to be passed to strftime() to format the clock.
    """
    div = "=" * len(time_string)

    while True:
        try:
            system("/usr/bin/clear")  # noqa: S605
            print(div)
            print(f"{datetime.now().strftime(time_string)}")  # noqa: DTZ005
            print(div)
            sleep(1)

        except KeyboardInterrupt:
            print()
            sys_exit(0)


if __name__ == "__main__":
    args = get_arguments()

    run_clock("%I:%M:%S %p" if args.twelve else "%H:%M:%S")
