#!/usr/bin/env python3
# Copyright (C) 2025
# Author:       Casey Sparks
# Date:         February 09, 2022.
# Description:
"""Display information about a network interface."""

from argparse import ArgumentParser, Namespace
from collections.abc import Iterator
from fcntl import ioctl
from logging import Formatter, StreamHandler, getLogger
from pathlib import Path
from socket import AF_INET, SOCK_DGRAM, inet_ntoa, socket
from struct import pack

from requests import get

LOG = getLogger(__name__)


def get_arguments() -> Namespace:
    """Get cmdline arguments.

    Returns:
        argparse.Namespace instance of user arguments.
    """
    parser = ArgumentParser(description=__doc__)

    parser.add_argument(  # --interface
        "-i",
        "--interface",
        dest="interface",
        type=str,
        help='Specify the network interface (like "eth0").',
    )
    parser.add_argument(  # --verbose
        "--verbose",
        "-v",
        dest="log_level",
        default=0,
        action="count",
        help="Specify logging verbosity. Default `CRITICAL`.",
    )

    arguments = parser.parse_args()
    arguments.log_level = range(40, -1, -10)[min(arguments.log_level, 3)]

    return arguments


def enable_log(log_level: int = 30) -> None:
    """Enable logging and handle outputs.

    Args:
        log_level:   User-specified log level. Default WARNING.
    """
    formatter = Formatter('{asctime} {threadName:12} {levelname:8}: "{message}"', style="{")
    log_console = StreamHandler()  # Log to screen.

    log_console.setFormatter(formatter)  # Set log stream format.
    LOG.addHandler(log_console)  # Log to screen.
    LOG.setLevel(log_level)  # User-specified log_level.


def get_wan_interface() -> str:
    """Read the default gateway directly from /proc.

    Returns:
        The name of the WAN interface.
    """
    gw_iface_name = next(route for route in all_routes() if route[1] == "00000000")[0]

    LOG.debug("Gateway interface: %s", gw_iface_name)

    return gw_iface_name


def all_routes() -> Iterator[list]:
    """Iterator returning all routes read from '/proc/net/route'.

    Yields:
        All system network routes.
    """
    with Path("/proc/net/route").open(encoding="utf-8") as route_file:
        for line in route_file:
            route = line.strip().split()

            LOG.debug("Route: %s", route)

            yield route


def public_ip(stun_server: str = "https://ipinfo.io/ip") -> str:
    """Get our public IP address.

    Returns:
        The public IP address of the device.
    """
    public_ip_addr = get(stun_server, timeout=2).text

    LOG.debug("Public IP: %s", public_ip_addr)

    return public_ip_addr


def hex_to_octet(hex_data: str) -> str:
    """Convert hexadecimal data to usable octets.

    Args:
        hex_data:    Hex data to convert to octet notation.

    Returns:
        Octal notation of the input hexadecimal notation.
    """
    LOG.debug("Converting hex data (%s) to octet.", hex_data)

    octet = inet_ntoa(pack("<L", int(hex_data, 16)))

    LOG.debug("Octet: %s", octet)

    return octet


def interface_info(iface: str) -> tuple:
    """Get the default gateway.

    Args:
        iface:           The network interface to query.

    Returns:
        Tuple of: (str(iface_ip), str(iface_gateway), str(iface_netmask))
    """
    sock = socket(AF_INET, SOCK_DGRAM)  # Open a socket.
    iface_ip = inet_ntoa(ioctl(sock.fileno(), 0x8915, pack("256s", bytes(iface[:15], "utf-8")))[20:24])
    iface_gateway = hex_to_octet(
        next(route for route in all_routes() if route[0] == iface and route[1] == "00000000")[2]
    )
    iface_netmask = hex_to_octet(
        next(
            route
            for route in all_routes()
            if route[0] == iface  # Is spec'd iface
            and route[7] != "00000000"  # Is not WAN gateway iface
        )[7]
    )

    LOG.debug("Netmask: %s", iface_netmask)
    LOG.debug("Gateway: %s", iface_gateway)
    LOG.debug("IP: %s", iface_ip)

    return iface_ip, iface_gateway, iface_netmask


def print_table(iface: str) -> None:
    """Create and print a table.

    Args:
        iface: The network interface to tabulate.
    """
    head_foot = 34 * "-"  # For table formatting
    ip_address, gateway, netmask = interface_info(iface)
    table = [
        [head_foot, ""],
        [iface, ""],
        [head_foot, ""],
        ["Interface", iface],
        ["Public IP", public_ip()],
        ["Local IP", ip_address],
        ["Gateway", gateway],
        ["Netmask", netmask],
        [head_foot, ""],
    ]

    for heading, data in table:
        print(f"{heading:<18}{data:>16}")


if __name__ == "__main__":
    args = get_arguments()

    enable_log(args.log_level)

    interface = args.interface or get_wan_interface()

    print_table(interface)
