#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# Name:         shannon
# Author:       Casey Sparks
# Date:         November 27, 2023
# Description:
'''Calculate the Shannon entropy of a string.'''

from argparse import ArgumentParser, Namespace
from collections import Counter
from locale import setlocale, LC_ALL
from math import log

setlocale(LC_ALL, 'en_US.UTF-8')                                                # Set locale.


def get_arguments() -> Namespace:
    '''
    Get cmdline arguments.
        :return:    argparse.Namespace instance of user arguments.
    '''
    parser = ArgumentParser(description=__doc__)                                # Instantiate argument parser.

    parser.add_argument(                                                        # Strings.
        'strings',
        type=str,
        nargs='+',
        help='The string to calculate entropy for.',
        )

    return parser.parse_args()                                                  # Parse arguments.


def shannon(
    string: str,
        ) -> float:
    '''
    Calculate the Shannon entropy of a string.
        :param string:  The string to calculate entropy for.
        :return:        Shannon entropy of 'string'.
    '''
    return - sum(f * log(f, 2) for f in [i / len(string) for i in Counter(string).values()])


if __name__ == '__main__':
    for s in get_arguments().strings:
        print(f'{s : <32}{shannon(s)}')
