---
- name: "[environment.packages] Collect package facts"
  ansible.builtin.package_facts:
  register: "packages_state"

- name: "[environment.packages.remove_snap]"
  when: "ansible_distribution == 'Ubuntu' and packages_state.packages['snapd']"
  become: true
  tags:
    - "packages"
    - "uninstall"
    - "snap"
  block:
    - name: "[environment.packages.remove_snap.collect_facts]"
      ansible.builtin.service_facts:
      register: "services_state"

    - name: "[environment.packages.remove_snap.debug_facts]"
      ansible.builtin.debug:
        var: "{{ services_state.services }}"
        verbosity: 3

    - name: "[environment.packages.remove_snap.systemd_service]"
      when: "services_state.ansible_facts.services['snapd.service']"
      ansible.builtin.systemd_service:
        name: "snapd.service"
        state: "stopped"
        enabled: false
        masked: true

    - name: "[environment.packages.remove_snap.uninstall]"
      ansible.builtin.apt:
        name: "snapd"
        state: "absent"
        purge: true
        autoclean: true
        autoremove: true
        force: true

    - name: "[environment.packages.remove_snap.apt_hold]"
      ansible.builtin.dpkg_selections:
        name: "snapd"
        selection: "hold"

    - name: "[environment.packages.remove_snap.apt_preferences]"
      ansible.builtin.copy:
        dest: "/etc/apt/preferences.d/nosnap.pref"
        force: true
        owner: "root"
        group: "root"
        mode: "0644"
        content: |
          Package: snapd
          Pin: release a=*
          Pin-Priority: -10

    - name: "[environment.packages.remove_snap.directories]"
      loop:
        - "/snap/"
        - "/var/lib/snapd/"
        - "/var/snap/"
        - "/root/snapd/"
      ansible.builtin.file:
        name: "{{ item }}"
        state: "absent"

    - name: "[environment.packages.remove_snap.apt_cache]"
      ansible.builtin.apt:
        update_cache: true

    - name: "[environment.packages.remove_snap.find_home_directories]"
      register: "user_snap_dirs"
      ansible.builtin.find:
        paths: "/home"
        depth: 2
        file_type: "directory"
        recurse: true
        patterns: "snap"

    - name: "[environment.packages.remove_snap.debug_home_directories]"
      ansible.builtin.debug:
        var: "{{ user_snap_dirs }}"
        verbosity: 3

    - name: "[environment.packages.remove_snap.remove_home_directories]"
      when: "user_snap_dirs.files | length > 0"
      loop: "{{ user_snap_dirs.files }}"
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: "absent"

- name: "[environment.uninstall_packages]"
  become: true
  tags:
    - "packages"
    - "uninstall"
  block:
    - name: "[environment.packages.uninstall]"
      tags: ["apt"]
      when: "ansible_os_family == 'Debian'"
      loop: "{{ environment_packages.unwanted.apt }}"
      ansible.builtin.apt:
        name: "{{ item }}"
        state: "absent"
        autoremove: true
        purge: true
        clean: true

    - name: "[environment.packages.uninstall]"
      tags: ["dnf"]
      when: "ansible_os_family == 'RHEL'"
      loop: "{{ environment_packages.unwanted.dnf }}"
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: "absent"
        autoremove: true

    - name: "[environment.packages.uninstall]"
      tags: ["pacman"]
      when: "ansible_os_family == 'ArchLinux'"
      loop: "{{ environment_packages.unwanted.pacman }}"
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: "absent"

- name: "[environment.packages.system.uninstall]"
  become: true
  tags:
    - "packages"
    - "install"
  block:
    - name: "[environment.packages.system.install]"
      tags: ["apt"]
      when: "ansible_os_family == 'Debian'"
      loop: "{{ environment_packages.wanted.apt }}"
      ansible.builtin.apt:
        name: "{{ item }}"
        state: "present"
        update_cache: true
        purge: true
        autoremove: true
        clean: true
        cache_valid_time: 3600                                                  # 1hr.

    - name: "[environment.packages.system.install]"
      tags: ["dnf"]
      when: "ansible_os_family == 'RHEL'"
      loop: "{{ environment_packages.wanted.dnf }}"
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: "present"

    - name: "[environment.packages.system.install]"
      tags: ["pacman"]
      when: "ansible_os_family == 'ArchLinux'"
      loop: "{{ environment_packages.wanted.pacman }}"
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: "present"

- name: "[environment.packages.pip]"
  tags:
    - "packages"
    - "install"
    - "python"
    - "pip"
  ansible.builtin.pip:
    name: "{{ environment_packages.wanted.python }}"
