---
- name: "[security.ulimit]"
  become: true
  tags: ["ulimit"]
  block:
    - name: "[security.ulimit.create_dir]"
      ansible.builtin.file:
        path: "/etc/security/limits.d"
        owner: "root"
        group: "root"
        mode: "0755"
        state: "directory"

    - name: "[security.ulimit.configure]"
      loop: "security_ulimits"
      community.general.pam_limits:
        dest: "/etc/security/limits.d/hardening.conf"
        domain: "{{ item.domain }}"
        limit_type: "{{ item.type }}"
        limit_item: "{{ item.item }}"
        value: "{{ item.value }}"
