---
# Author:       Casey Sparks
# Date:         June 06, 2024
# Description:  Yamllint configuration for yamllint.yml workflow.

extends: "default"
ignore:  # git submodules
  - "collections/caseysparkz/environment/roles/vim/files/vim/pack/plugins/start/nerdtree/**"
  - "collections/caseysparkz/environment/roles/vim/files/vim/pack/plugins/start/gnupg/**"
  - "collections/caseysparkz/environment/roles/vim/files/vim/pack/plugins/start/terraform/**"
  - "collections/caseysparkz/environment/roles/vim/files/vim/pack/plugins/start/ale/**"
rules:
  braces:
    level: "warning"
    max-spaces-inside: 1
  brackets:
    level: "warning"
    max-spaces-inside: 1
  colons:
    level: "warning"
  commas:
    level: "warning"
  comments-indentation: "disable"
  empty-lines:
    level: "warning"
  hyphens:
    level: "warning"
  indentation:
    level: "warning"
    indent-sequences: "consistent"
  line-length:
    max: 120
    level: "warning"
    allow-non-breakable-inline-mappings: true
  truthy:
    ignore: [".github/workflows/*"]
