#!/usr/bin/env sh
# -*- coding:utf-8 -*-

xrandr                          \
    --output eDP-1              \
        --off                   \
    --output HDMI-1             \
        --off                   \
    --output DP-1               \
        --off                   \
    --output HDMI-2             \
        --off                   \
    --output DP-2               \
        --off                   \
    --output HDMI-3             \
        --off                   \
    --output DP-3               \
        --off                   \
    --output DP-4               \
        --off                   \
    --output DP-3-1             \
        --primary               \
        --mode 1920x1080        \
        --pos 1920x252          \
        --rotate normal         \
    --output DP-3-2             \
        --mode 1920x1080        \
        --pos 3840x0            \
        --rotate right          \
    --output DP-3-3             \
        --mode 1920x1080        \
        --pos 0x252             \
        --rotate normal
