---
environment_dotfiles:
  subdirectories:
    - path: "{{ ansible_env.HOME }}/.config/Yubico"
      owner: "{{ ansible_effective_user_id }}"
      group: "{{ ansible_effective_group_id }}"
      mode: "0700"
  symlinks:
    - src: "{{ role_path }}/files/config/pylint.pylintrc"
      dest: "{{ ansible_env.HOME }}/.config/pylint.pylintrc"
      mode: "0600"
    - src: "{{ role_path }}/files/config/Yubico/u2f_keys"
      dest: "{{ ansible_env.HOME }}/.config/Yubico/u2f_keys"
      mode: "0600"
    - src: "{{ role_path }}/files/config/yamllint.yml"
      dest: "{{ ansible_env.HOME }}/.config/yamllint.yml"
      mode: "0600"
    - src: "{{ role_path }}/files/screen/screenrc"
      dest: "{{ ansible_env.HOME }}/.screenrc"
      mode: "0600"
    - src: "{{ role_path }}/files/config/i3/"
      dest: "{{ ansible_env.HOME }}/.config/i3/"
      mode: "0700"
environment_packages:
  wanted:
    apt: []
    dnf: []
    pacman: []
    python:
      - "dict2xml>=1.7,<2.0"
      - "opencv-python>=4.8,<5.0"
      - "pandas>=1.5,<2.0"
      - "pillow>=10.1,<11.0"
      - "psutil>=5.9,<6.0"
      - "pyautogui>=0.9,<1.0"
      - "python-gnupg>=0.5,<1.0"
      - "qrcode>=7.4,<8.0"
      - "requests>=2.31,<3.0"
      - "tabulate>=0.9,<1.0"
      - "toml>=0.10,<1.0"
      - "xmltodict>=0.13,1.0"
  unwanted:
    apt: ["command-not-found"]
    dnf: []
