#!/usr/bin/env bash

xrandr                      \
    --output eDP-1 --off    \
    --output HDMI-1 --off   \
        --mode 1920x1080    \
        --pos 1920x291      \
        --rotate normal     \
    --output HDMI-2 --off   \
    --output DP-1 --off     \
    --output DP-1-1         \
    --output DP-1-2         \
    --output DP-1-3 --off   \
    --output DP-2 --off
