#!/usr/bin/env bash
#-*- coding:utf-8 -*-
cdc() {  # Change dir, clear terminal.
  cd "${1}" || exit 1
  clear
}

cdl() {  # Change dir, clear terminal, display dir contents.
  cd "${1}" || exit 1
  clear
  ls -l
}

mkcd() {  # Make/enter a dir.
  mkdir -p "${1}" && cd "${1}" || exit 1
}
