#!/usr/bin/env bash
#-*- coding:utf-8 -*-
# Export encrypted environment variables to bash session.
getsecrets() {
    FILE="${SECRETS}"

    if lsusb | grep --quiet --ignore-case 'yubikey'; then
        for LINE in $(gpg --decrypt "${FILE}" 2> /dev/null | grep -v "^#"); do
            export "${LINE?}"
        done
    fi
}
