#!/usr/bin/env bash
getsecrets(){  # Export encrypted environment variables to bash session.
    if lsusb | grep --quiet --ignore-case 'yubikey'; then
        for LINE in $(gpg --decrypt "${SECRETS}" 2> /dev/null | grep -v "^#"); do
            export "${LINE?}"
        done
    fi
}
