---
- name: "Configure git"
  tags: ["git"]
  when: "ansible_system == 'Linux'"
  ansible.builtin.file:
    src: "{{ role_path }}/gitconfig_linux"
    dest: "{{ ansible_env.HOME }}/.gitconfig"
    owner: "{{ ansible_effective_user_id }}"
    group: "{{ ansible_effective_group_id }}"
    state: "link"
    force: true

- name: "Configure git"
  tags: ["git"]
  when: "ansible_system == 'Darwin'"
  ansible.builtin.file:
    src: "{{ role_path }}/gitconfig_macos"
    dest: "{{ ansible_env.HOME }}/.gitconfig"
    owner: "{{ ansible_effective_user_id }}"
    group: "{{ ansible_effective_group_id }}"
    state: "link"
    force: true
