#!/usr/bin/env bash
nohup xrandr                        \
    --output eDP-1                  \
        --primary                   \
        --mode 1920x1200            \
        --pos 0x0                   \
        --rotate normal             \
    --output DP-3-1                 \
        --mode 1920x1080            \
        --pos 1920x0                \
        --rotate normal             \
    --output DP-3-2                 \
        --mode 1920x1080            \
        --pos 3840x0                \
        --rotate normal
