---
- name: "Find su binary"
  register: "privilegeescalation_supath"
  ansible.builtin.find:
    patterns: "^su$"
    paths:
      - "/bin"
      - "/usr/bin"

- name: "Disable su"
  become: true
  loop: "{{ privilegeescalation_supath.files }}"
  ansible.builtin.file:
    dest: "{{ item.path }}"
    owner: "root"
    group: "root"
    mode: "0700"
