#!/usr/bin/env bash
#-*- coding:utf-8 -*-
# docker-compose wrapper.
docker-compose(){
    case "$@" in
        up)
            command docker-compose up --no-log-prefix;;

        *)
            command docker-compose "$@"
    esac
}
