#!/usr/bin/env bash
#-*- coding:utf-8 -*-
# pip wrapper.
pip(){
    case "$@" in
        upgrade)
            command pip3 list --outdated            \
                | grep -v '^\-e'                    \
                | cut -d = -f 1                     \
                | xargs -n1 pip3 install --upgrade 
        ;;

        *)
            command pip "$@"
    esac
}
