#!/usr/bin/env sh
#-*- coding:utf-8 -*-
# Author:       Casey Sparks
# Date:         May 18, 2022
# Description:  Extract any compressed file or compress any uncompressed file.
# Notes:        Python refactor candidate.

for FILE in "${@}"; do
    if [ -f "${FILE}" ] ; then
        case "${FILE}" in
            *.tar|*.tar.xz)
                tar -xf "${FILE}";;

            *.tbz2|*.tar.bz2)
                tar -xjf "${FILE}";;

            *.tgz|*.tar.gz)
                tar -xzf "${FILE}";;

            *.bz2)
                bunzip2 "${FILE}";;

            *.rar)
                unrar x "${FILE}";;

            *.gz)
                gunzip "${FILE}";;

            *.xz)
                xz -d "${FILE}";;

            *.zip)
                unzip "${FILE}";;

            *.zst)
                zstd -d "${FILE}";;

            *.Z)
                uncompress "${FILE}";;

            *.7z)
                7z x "${FILE}";;

            *)
                tar -zcvf "${FILE}".tar.gz "${FILE}";;
        esac
    fi
done
