#!/usr/bin/env sh
#-*- coding:utf-8 -*-
# Author:       Casey Sparks
# Date:         May 18, 2022.
# Description:  A simple wrapper for xrandr scripts.

HOSTNAME="$(cat /etc/hostname)"

"${HOME}/.screenlayout/${HOSTNAME}/${1}"                                \
        > /dev/null 2>&1                                                \
    && exec betterlockscreen                                            \
        --update                                                        \
        "${HOME}"/Pictures/backgrounds/"${HOSTNAME}".*                  \
        >/dev/null 2>&1 &

command . "${HOME}/.bashrc"
