---
- name: "Find role certificates"
  register: "ca_certificates_files"
  ansible.builtin.find:
    paths: "{{ role_path }}/files/"
    file_type: "file"
    patterns: "*.pem"

- name: "Create CA trust directory"
  become: true
  when: "ansible_os_family in ['ArchLinux', 'Debian'] and ca_certificates_files.matched >= 1"
  ansible.builtin.file:
    path: "/usr/local/share/ca-certificates/"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0644"

- name: "Install CA certificates"
  become: true
  when: "ansible_os_family in ['ArchLinux', 'Debian'] and ca_certificates_files.matched >= 1"
  loop: "{{ ca_certificates_files.files }}"
  ansible.builtin.copy:
    src: "{{ item.path }}"
    dest: "/usr/local/share/ca-certificates/{{ item.path | basename }}"
    owner: "root"
    group: "root"
    mode: "0644"

- name: "Create CA trust directory"
  become: true
  when: "ansible_os_family == 'RedHat' and ca_certificates_files.matched >= 1"
  ansible.builtin.file:
    path: "/etc/pki/ca-trust/source/anchors/"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"

- name: "Install CA certificates"
  become: true
  when: "ansible_os_family == 'RedHat' and ca_certificates_files.matched >= 1"
  loop: "{{ ca_certificates_files.files }}"
  ansible.builtin.copy:
    src: "{{ item.path }}"
    dest: "/etc/pki/ca-trust/source/anchors/{{ item.path | basename }}"
    owner: "root"
    group: "root"
    mode: "0644"

- name: "Update CA trust"
  become: true
  ansible.builtin.command: "update-ca-certificates"
  changed_when: false
