---
- name: "Set 'gnupg_symlink_src_dir'"
  ansible.builtin.set_fact:
    gnupg_symlink_src_dir: "{{ role_path | replace(collections_path, inventory_dir ~ '/collections') }}"

- name: "Install gpg"
  become: true
  tags: ["apt"]
  when: "ansible_facts.os_family == 'Debian'"
  ansible.builtin.apt:
    pkg:
      - "gnupg"
      - "gnupg-agent"
      - "gnupg-utils"
    state: "present"
    update_cache: true
    cache_valid_time: 3600

- name: "Install gpg"
  tags: ["homebrew"]
  when: "ansible_facts.os_family == 'Darwin'"
  community.general.homebrew:
    name:
      - "gnupg"
      - "gnupg-pkcs11-scd"
    state: "present"
    update_homebrew: true

- name: "Create ~/.gnupg"
  tags: ["gnupg"]
  ansible.builtin.file:
    path: "{{ ansible_facts.env.HOME }}/.gnupg/"
    state: "directory"
    mode: "0700"

- name: "Install ~/.gnupg/gpg-agent.conf"
  tags: ["gnupg"]
  ansible.builtin.file:
    src: "{{ gnupg_symlink_src_dir }}/files/gpg-agent.conf.{{ ansible_facts.os_family }}"
    dest: "{{ ansible_facts.env.HOME }}/.gnupg/gpg-agent.conf"
    state: "link"
    force: true

- name: "Install ~/.gnupg/gpg.conf"
  tags: ["gnupg"]
  ansible.builtin.file:
    src: "{{ gnupg_symlink_src_dir }}/files/gpg.conf"
    path: "{{ ansible_facts.env.HOME }}/.gnupg/gpg.conf"
    state: "link"
    force: true

- name: "Find role pubkeys"
  tags: ["gnupg"]
  register: "gnupg_pubkeys"
  ansible.builtin.find:
    paths: "{{ gnupg_symlink_src_dir }}/files/pubkeys/"
    patterns:
      - "*.asc"
      - "*.gpg"
    file_type: "file"
    recurse: false

- name: "Import role pubkeys"
  tags: ["gnupg"]
  loop: "{{ gnupg_pubkeys.files }}"
  changed_when: false
  ansible.builtin.command:
    cmd: "gpg --import {{ item.path }}"
