# Author:       Casey Sparks
# Date:         November 15, 2023
# Description:  Run ansible-lint against Ansible configs on push and PR.
---
name: "Validate Ansible code"
on:
  pull_request:
    branches: ["main"]
    paths:
      - "collections/**/*.yml"
      - "hosts/**/*.yml"
      - "playbooks/**/*.yml"
    types:
      - "opened"
      - "ready_for_review"
      - "reopened"
      - "synchronize"
jobs:
  ansible_lint:
    name: "Ansible Lint"
    runs-on: "ubuntu-latest"
    env:
      ANSIBLE_CACHE_KEY: "ansible-cache"
      ANSIBLE_CACHE_PATH: "${{ github.workspace }}/ansible/collections/ansible_collections/"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10"  # v6.0.3
        with:
          fetch-depth: 0

      - name: "Restore Ansible cache"
        id: "ansible-cache"
        uses: "actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae"  # v5.0.5
        with:
          key: "${{ env.ANSIBLE_CACHE_KEY }}"
          path: "${{ env.ANSIBLE_CACHE_PATH }}"

      - name: "Run ansible-lint"
        uses: "ansible/ansible-lint@5fac056c45595896c973fbde871f01f6cb14d74c"  # v26.4.0
        with:
          args: ""
          working_directory: "${{ github.workspace }}/ansible/"
          requirements_file: "requirements.yml"
          setup_python: true

      - name: "Save Ansible cache"
        uses: "actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae"  # v5.0.5
        with:
          key: "${{ steps.ansible-cache.outputs.cache-primary-key }}"
          path: "${{ env.ANSIBLE_CACHE_PATH }}"
